name: Build Kivy APK

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
      ANDROID_SDK_ROOT: $HOME/android-sdk
      PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip ...

      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install cython==0.29.19 buildozer

      - name: Install Android cmdline-tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-*.zip
          mv cmdline-tools latest

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      - name: Install required SDK packages
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-30" "build-tools;36.0.0" "ndk;25.1.8937393"

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk
